# Generated by Django 5.1.6 on 2025-05-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.PositiveIntegerField()),
                ('house_number_addition', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=20)),
                ('construction_year', models.PositiveIntegerField()),
                ('has_garage', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
