# Generated by Django 5.2.1 on 2025-05-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
