# Generated by Django 5.2.1 on 2025-05-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
